import React from 'react'
import Head from "next/head"
import Image from "next/image"

import LogoInstagram from '../assets/instagram-icon.svg'
import logoTwitter from '../assets/twitter-logo.png'

const Home: React.FC = () => {
  return (
    <div >
      <Head>
        <title>My setup - react</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
          <LogoInstagram />
          <Image src={logoTwitter} alt="" width="200" height="200"/>
        <h1>
          Olá mundo, Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}

export default Home
