import React from 'react'
import Head from "next/head"
import Image from "next/image"
import Link from 'next/link'
import Hello from './hello'

// import LogoInstagram from '../assets/instagram-icon.svg'
// import logoTwitter from '../assets/twitter-logo.png'

const Home: React.FC = () => {
  return (
    <div >
      <Head>
        <title>My setup - react</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        {/* <LogoInstagram /> */}
        {/* <Image src={logoTwitter} alt="" /> */}
        <h1>
          Isso é o index geral
        </h1>
        <h1>
          <Link href={'/hello'}>
            <a>Diga Hello</a>
          </Link>
        </h1>
        <h1>
          <Link href={'/soultech'}>
            <a>Ir para a plataforma Soultech</a>
          </Link>
        </h1>
        <h1>
          <Link href={'/telessaude'}>
            <a>Ir para a plataforma de Agendamentos</a>
          </Link>
        </h1>
        <h1>
          <Link href="/loadRepositories">
            <a>Ver Meus Repositórios</a>
          </Link>
        </h1>
        <h1>
          <Link href="/dinamica">
            <a>Ver Meus Testes de Rotas Dinamicas</a>
          </Link>
        </h1>
      </main>
    </div>
  )
}

export default Home